### PR TITLE
[E105-MG < T0796-MG] Add mocha as dependency

### PR DESCRIPTION
**Pull request by kostasrim**

### CODE REVIEW

**Comment by gitbuda** [comment]
The same here as on #3, `node_ modules` shouldn't be committed?

**Comment by antaljanosbenjamin** [comment]
What should I check in this PR? to be honest I am a bit lost here, not sure what worth to check.

**Review by gitbuda — APPROVED** [review]

**Review by gitbuda — CHANGES_REQUESTED** [review]
This is testing, so it should also be under dev deps 😄

**Review by jbajic — APPROVED** [review]

**Comment by kostasrim** [comment]
@antaljanosbenjamin it just adds the deps. It's a boilerplate. 
@gitbuda moved mocha to devDeps -- you learn every day!

**Review by gitbuda — APPROVED** [review]

**Pull request merged**
